export const brLogos: Record<string, string> = {
  "Botafogo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Botafogo_de_Futebol_e_Regatas_logo.svg/250px-Botafogo_de_Futebol_e_Regatas_logo.svg.png",
  "Palmeiras": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/SE_Palmeiras_2025_crest.png/250px-SE_Palmeiras_2025_crest.png",
  "Flamengo": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Clube_de_Regatas_do_Flamengo_logo.svg/250px-Clube_de_Regatas_do_Flamengo_logo.svg.png",
  "Grêmio": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Gremio_logo.svg/250px-Gremio_logo.svg.png",
  "Corinthians": "https://upload.wikimedia.org/wikipedia/pt/thumb/b/b4/Corinthians_simbolo.png/250px-Corinthians_simbolo.png",
  "Coritiba": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Coritiba_Foot_Ball_Club_logo.svg/250px-Coritiba_Foot_Ball_Club_logo.svg.png",
  "Internacional": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sport_Club_Internacional_logo.svg/250px-Sport_Club_Internacional_logo.svg.png",
  "São Paulo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/S%C3%A3o_Paulo_Futebol_Clube_logo_%282022%29.svg/250px-S%C3%A3o_Paulo_Futebol_Clube_logo_%282022%29.svg.png",
  "Cruzeiro": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Cruzeiro_Esporte_Clube_%28logo%29.svg/250px-Cruzeiro_Esporte_Clube_%28logo%29.svg.png",
  "Atlético Mineiro": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Atletico_mineiro_galo.png/250px-Atletico_mineiro_galo.png",
  "Vasco da Gama": "https://upload.wikimedia.org/wikipedia/pt/thumb/8/8b/EscudoDoVascoDaGama.svg/250px-EscudoDoVascoDaGama.svg.png",
  "Fluminense": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Fluminense_Football_Club.svg/250px-Fluminense_Football_Club.svg.png",
  "Bahia": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Esporte_Clube_Bahia_logo.svg/250px-Esporte_Clube_Bahia_logo.svg.png",
  "Santos": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Santos_Futebol_Clube_logo_%28with_stars_and_crown%29.png/250px-Santos_Futebol_Clube_logo_%28with_stars_and_crown%29.png",
  "Red Bull Bragantino": "https://upload.wikimedia.org/wikipedia/pt/thumb/9/9e/RedBullBragantino.png/250px-RedBullBragantino.png",
  "Vitória": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Esporte_Clube_Vit%C3%B3ria_%282024%29.svg/120px-Esporte_Clube_Vit%C3%B3ria_%282024%29.svg.png",
  "Mirassol": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Mirassol_Futebol_Clube_logo_%283_stars%29.png/250px-Mirassol_Futebol_Clube_logo_%283_stars%29.png",
  "Chapecoense": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Logo_Associa%C3%A7%C3%A3o_Chapecoense_de_Futebol.svg/120px-Logo_Associa%C3%A7%C3%A3o_Chapecoense_de_Futebol.svg.png",
  "Athletico Paranaense": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Athletico_Paranaense_%28Logo_2019%29.svg/250px-Athletico_Paranaense_%28Logo_2019%29.svg.png",
  "Remo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Clube_do_Remo.svg/250px-Clube_do_Remo.svg.png",
  "América Mineiro": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Escudo_oficial_do_Am%C3%A9rica_Futebol_Clube.svg/250px-Escudo_oficial_do_Am%C3%A9rica_Futebol_Clube.svg.png",
  "Sport": "https://upload.wikimedia.org/wikipedia/pt/thumb/1/17/Sport_Club_do_Recife.png/120px-Sport_Club_do_Recife.png",
  "Athletic": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Athletic_Club_%28Minas_Gerais%29.svg/120px-Athletic_Club_%28Minas_Gerais%29.svg.png",
  "São Bernardo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/S%C3%A3o_Bernardo_FC_2020_crest.png/250px-S%C3%A3o_Bernardo_FC_2020_crest.png",
  "Atlético Goianiense": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Atl%C3%A9tico_Goianiense_logo_%28sem_estrelas%29.png/250px-Atl%C3%A9tico_Goianiense_logo_%28sem_estrelas%29.png",
  "Vila Nova": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Vila_Nova_Logo_Oficial.svg/250px-Vila_Nova_Logo_Oficial.svg.png",
  "Avaí": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ava%C3%AD_Futebol_Clube_logo.svg/120px-Ava%C3%AD_Futebol_Clube_logo.svg.png",
  "Botafogo-SP": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Botafogo_Futebol_Clube.svg/250px-Botafogo_Futebol_Clube.svg.png",
  "CRB": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/CRB_logo.svg/250px-CRB_logo.svg.png",
  "Ceará": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cear%C3%A1_Sporting_Club_logo.svg/120px-Cear%C3%A1_Sporting_Club_logo.svg.png",
  "Criciúma": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Crici%C3%BAma_EC_2025_crest.svg/120px-Crici%C3%BAma_EC_2025_crest.svg.png",
  "Cuiabá": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Cuiab%C3%A1_EC_crest.png/120px-Cuiab%C3%A1_EC_crest.png",
  "Fortaleza": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Fortaleza_Esporte_Clube_logo.png/250px-Fortaleza_Esporte_Clube_logo.png",
  "Goiás": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Goi%C3%A1s_Esporte_Clube_logo.svg/250px-Goi%C3%A1s_Esporte_Clube_logo.svg.png",
  "Juventude": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Juventude_crest.png/250px-Juventude_crest.png",
  "Londrina": "https://upload.wikimedia.org/wikipedia/pt/thumb/9/96/Londrina_EC.png/120px-Londrina_EC.png",
  "Novorizontino": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Gr%C3%AAmio_Novorizontino.svg/120px-Gr%C3%AAmio_Novorizontino.svg.png",
  "Náutico": "https://upload.wikimedia.org/wikipedia/pt/thumb/d/de/Simbolo-escudo-nautico.png/120px-Simbolo-escudo-nautico.png",
  "Operário-PR": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Oper%C3%A1rio_Ferrovi%C3%A1rio_EC_%28no_stars%29.png/120px-Oper%C3%A1rio_Ferrovi%C3%A1rio_EC_%28no_stars%29.png",
  "Guarani": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Guarani_Futebol_Clube_logo.svg/250px-Guarani_Futebol_Clube_logo.svg.png",
};
